version: "3.1"
services:
  db-service:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "todos"
      POSTGRES_USER: "rahul"
      POSTGRES_PASSWORD: "rahul@123"
      # MYSQL_ROOT_PASSWORD: "password"

  web-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db-service
